name: Build and Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Cache pnpm packages
      id: pnpm-cache
      uses: actions/cache@v3
      with:
        path: web/themes/custom/f3k3_holy/node_modules
        key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-

    - name: Install dependencies
      run: |
        composer install --prefer-dist --no-progress
        cd web/themes/custom/f3k3_holy
        pnpm i

    - name: Build theme
      run: cd web/themes/custom/f3k3_holy &&

    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v4
      with:
        name: php-app
        path: .

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md
