name: Build and Deploy

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Download artifact from previous build
        uses: actions/download-artifact@v4
        with:
          name: php-app
          path: .

      - name: Deploy to Staging server
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_KEY }}
          ARGS: "-rlgoDzvc -i"
          SOURCE: "."
          REMOTE_HOST: ${{ vars.DEPLOY_HOST }}
          REMOTE_USER: ${{ vars.DEPLOY_USER }}
          TARGET: ${{ vars.DEPLOY_PATH }}
          EXCLUDE: "vendor, .git"
          SCRIPT_BEFORE: |
            whoami
            ls -al
          SCRIPT_AFTER: |
            cd ${{ vars.DEPLOY_PATH }}
            composer install --prefer-dist --no-progress
            ./vendor/bin/drush deploy