name: Build and Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-


    - name: Install dependencies
      run: |
        composer install --prefer-dist --no-progress

    - name: Build theme
      run: cd web/themes/custom/f3k3_holy &&

    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v4
      with:
        name: php-app
        path: .

  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: php-app
          path: .
      - uses: contention/rsync-deployments@v2.0.0
        with:
          USER: ${{ vars.DEPLOY_USER }}
          HOST: ${{ vars.DEPLOY_HOST }}
          LOCALPATH: .
          REMOTEPATH: ${{ vars.DEPLOY_PATH }}
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}